little rework
SnailyCAD/snaily-cadv4 pull request #945
Opened 2022-07-02 16:50 UTC by subtosharki

## Bug

- [ ] Related issues linked using `closes: #number`

## Feature

- [ ] Related issues linked using `closes: #number`
- [ ] There is only 1 db migration with no breaking changes.

## Translations

- [ ] `.json` files are formatted: `yarn format`
- [ ] Translations are correct
- [ ] New translation? It's been added to `next.config.js`

2022-07-02 16:51 UTC, subtosharki commented
https://github.com/SnailyCAD/snaily-cadv4/issues/944

2022-07-02 16:54 UTC, subtosharki commented
- [x] /v1/admin 
- [x] /v1/admin/import/citizens 
- [x] /v1/admin/import/vehicles 
- [x] /v1/admin/import/weapons 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

2022-07-02 17:14 UTC, subtosharki commented
@Dev-CasperTheGhost im going to leave the body/schema rework part to you as you know better what is needed

2022-07-03 07:24 UTC, Dev-CasperTheGhost requested changes
Added a few suggestions, will commit these myself here:)

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/AdminController.ts
> +  @Description("Get all the users within the CAD")
```suggestion
  @Description("Get simple CAD stats")
```

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/import/ImportCitizensController.ts
> +  @Description("Import Citizens in the CAD via file upload")
```suggestion
  @Description("Import citizens in the CAD via file upload")
```

minor casing typo

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/import/ImportVehiclesController.ts
> +  @Description("Get All the Vehciles in the CAD")
```suggestion
  @Description("Get all the vehicles in the CAD (paginated)")
```

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/import/ImportVehiclesController.ts
> +  @Description("Import Vehciles in the CAD via file upload")
```suggestion
  @Description("Import vehicles in the CAD via file upload")
```

minor typo

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/import/ImportWeaponsController.ts
> +  @Description("Get All the Weapons in the CAD")
```suggestion
  @Description("Get all the Weapons in the CAD (paginated)")
```

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/import/ImportWeaponsController.ts
> +  @Description("Import Vehciles in the CAD via file upload")
```suggestion
  @Description("Import weapons in the CAD via file upload")
```

should be weapons not vehicles here

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/manage/AdminManageCustomFieldsController.ts
> +  @Description("Update a custom field")
```suggestion
  @Description("Update a custom field by its id")
```

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/manage/AdminManageCustomFieldsController.ts
> +  @Description("Delete a custom field")
```suggestion
  @Description("Delete a custom field by its id")
```

2022-07-03 07:24 UTC, Dev-CasperTheGhost commented on packages/api/src/controllers/admin/manage/AdminManageCustomFieldsController.ts
> +  @Description("")
```suggestion
  @Description("Create a new custom field")
```

2022-07-03 07:32 UTC, Dev-CasperTheGhost approved these changes

2022-07-03 07:32 UTC, merged